name: Simple CI

on:
  push:
    branches: [ main, develop, fix-preview ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Lua
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.4
        
    - name: Check Lua syntax
      run: |
        echo "Checking Lua syntax..."
        find lua/ -name "*.lua" -type f | while read file; do
          echo "Checking $file"
          lua5.4 -c "$file" || exit 1
        done
        lua5.4 -c mcp-server.lua
        find mcp-servers/ -name "*.lua" -type f | while read file; do
          echo "Checking $file"  
          lua5.4 -c "$file" || exit 1
        done
        echo "All syntax checks passed!"
        
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Lua
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.4
        
    - name: Run tests
      run: |
        cd tests
        lua5.4 run_all_tests.lua || echo "Tests completed with status $?"
        
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint with luacheck
      uses: lunarmodules/luacheck@v1
      with:
        args: . --ignore 212 213 611 612 613 614 631 --exclude-files .luarocks --exclude-files tests/mocks